kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: op-demo-front
subjects:
- kind: ServiceAccount
  name: op-demo-front
roleRef:
  kind: Role
  name: op-demo-front
  apiGroup: rbac.authorization.k8s.io
